const ActionTypes = {
    GET_BARANG : 'GET_BARANG',
    GET_BARANG_SUCCEED : 'GET_BARANG_SUCCEED',
    GET_BARANG_FAILED : 'GET_BARANG_FAILED',
    ADD_BARANG : 'ADD_BARANG',
    ADD_BARANG_SUCCEED : 'ADD_BARANG_SUCCEED',
    ADD_BARANG_FAILED : 'ADD_BARANG_FAILED',
    EDIT_BARANG : 'EDIT_BARANG',
    EDIT_BARANG_SUCCEED : 'EDIT_BARANG_SUCCEED',
    EDIT_BARANG_FAILED : 'EDIT_BARANG_FAILED',
    DELETE_BARANG : 'DELETE_BARANG',
    DELETE_BARANG_SUCCEED : 'DELETE_BARANG_SUCCEED',
    DELETE_BARANG_FAILED : 'DELETE_BARANG_FAILED',

    LOGIN_USER : 'LOGIN_USER',
    LOGIN_USER_SUCCEED : 'LOGIN_USER_SUCCEED',
    LOGIN_USER_FAILED : 'LOGIN_USER_FAILED'
}

export default ActionTypes